language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      script:
        - ./autogen.sh
        - ./build-windows-binaries.sh
        - ./build-windows-package.sh
    - os: linux
      dist: bionic
      compiler: clang
      script:
        - ./autogen.sh
        - ./build-linux-binaries.sh
    - os: linux
      dist: bionic
      compiler: gcc
      script:
        - ./autogen.sh
        - ./build-linux-binaries.sh
    - os: linux
      dist: bionic
      script:
        - ./autogen.sh
        - ./build-linux-package.sh -us -uc
    - os: osx
      script:
        - ./autogen.sh
        - ./build-mac-binaries.sh
arch:
  - ppc64le
addons:
  apt:
    packages:
      # For Debian packaging
      - devscripts
      - fakeroot
      - build-essential
      - debhelper
      - cdbs
      # For cross-compiling Windows executables
      - mingw-w64
      - dos2unix
      - groff
