language: cpp
os: linux
dist: bionic
compiler:
- gcc
- clang
arch:
- amd64
- arm64
- ppc64le
- s390x
script:
  - ./autogen.sh
  - ./build-linux-binaries.sh

jobs:
  include:
    - os: linux
      dist: bionic
      name: "Windows"
      script:
        - ./autogen.sh
        - ./build-windows-binaries.sh
        - ./build-windows-package.sh
    - os: linux
      dist: bionic
      name: "Ubuntu package"
      script:
        - ./autogen.sh
        - ./build-linux-package.sh -us -uc
    - os: osx
      name: "macOS"
      script:
        - ./autogen.sh
        - ./build-mac-binaries.sh

addons:
  apt:
    packages:
      # For Debian packaging
      - devscripts
      - fakeroot
      - build-essential
      - debhelper
      - cdbs
      # For cross-compiling Windows executables
      - mingw-w64
      - dos2unix
      - groff
